# kozuchi version
# リリースしたら直後に上げること

KOZUCHI_MAJOR_VERSION  = 3
KOZUCHI_MIDDLE_VERSION = 1
KOZUCHI_MINORE_VERSION = 3

KOZUCHI_VERSION = "#{KOZUCHI_MAJOR_VERSION}.#{KOZUCHI_MIDDLE_VERSION}.#{KOZUCHI_MINORE_VERSION}"
