# kozuchi version

KOZUCHI_MAJOR_VERSION  = 0
KOZUCHI_MIDDLE_VERSION = 14
KOZUCHI_MINORE_VERSION = 5

KOZUCHI_VERSION = "#{KOZUCHI_MAJOR_VERSION}.#{KOZUCHI_MIDDLE_VERSION}.#{KOZUCHI_MINORE_VERSION}"
