# kozuchi version

KOZUCHI_MAJOR_VERSION  = 0
KOZUCHI_MIDDLE_VERSION = 8
KOZUCHI_MINORE_VERSION = 1

KOZUCHI_VERSION = "#{KOZUCHI_MAJOR_VERSION}.#{KOZUCHI_MIDDLE_VERSION}.#{KOZUCHI_MINORE_VERSION}"
