# kozuchi version

KOZUCHI_MAJOR_VERSION  = 0
KOZUCHI_MIDDLE_VERSION = 16
KOZUCHI_MINORE_VERSION = 3

KOZUCHI_VERSION = "#{KOZUCHI_MAJOR_VERSION}.#{KOZUCHI_MIDDLE_VERSION}.#{KOZUCHI_MINORE_VERSION}"
