# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 10) do

  create_table "account_entries", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "account_id", :integer, :default => 0, :null => false
    t.column "deal_id", :integer, :default => 0, :null => false
    t.column "amount", :integer, :default => 0, :null => false
    t.column "balance", :integer
    t.column "friend_link_id", :integer
    t.column "settlement_id", :integer
    t.column "result_settlement_id", :integer
  end

  add_index "account_entries", ["account_id"], :name => "account_entries_account_id_index"
  add_index "account_entries", ["deal_id"], :name => "account_entries_deal_id_index"
  add_index "account_entries", ["user_id"], :name => "account_entries_user_id_index"
  add_index "account_entries", ["friend_link_id"], :name => "account_entries_friend_link_id_index"
  add_index "account_entries", ["settlement_id"], :name => "account_entries_settlement_id_index"
  add_index "account_entries", ["result_settlement_id"], :name => "account_entries_result_settlement_id_index"

  create_table "account_links", :id => false, :force => true do |t|
    t.column "account_id", :integer, :default => 0, :null => false
    t.column "connected_account_id", :integer, :default => 0, :null => false
  end

  add_index "account_links", ["account_id"], :name => "account_links_account_id_index"
  add_index "account_links", ["connected_account_id"], :name => "account_links_connected_account_id_index"

  create_table "account_rules", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "account_id", :integer, :default => 0, :null => false
    t.column "associated_account_id", :integer, :default => 0, :null => false
    t.column "closing_day", :integer, :default => 0, :null => false
    t.column "payment_term_months", :integer, :default => 1, :null => false
    t.column "payment_day", :integer, :default => 0, :null => false
  end

  create_table "accounts", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "name", :string, :limit => 32, :default => "", :null => false
    t.column "account_type_code", :integer
    t.column "asset_type_code", :integer
    t.column "sort_key", :integer
    t.column "partner_account_id", :integer
    t.column "type", :text
  end

  add_index "accounts", ["user_id"], :name => "accounts_user_id_index"
  add_index "accounts", ["partner_account_id"], :name => "accounts_partner_account_id_index"

  create_table "admin_users", :force => true do |t|
    t.column "name", :string
    t.column "hashed_password", :string, :limit => 40
  end

  create_table "deal_links", :force => true do |t|
    t.column "created_user_id", :integer
  end

  create_table "deals", :force => true do |t|
    t.column "type", :string, :limit => 20, :default => "", :null => false
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "date", :date, :null => false
    t.column "daily_seq", :integer, :default => 0, :null => false
    t.column "summary", :string, :limit => 64, :default => "", :null => false
    t.column "confirmed", :boolean, :default => true, :null => false
    t.column "parent_deal_id", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "deals", ["user_id"], :name => "deals_user_id_index"
  add_index "deals", ["parent_deal_id"], :name => "deals_parent_deal_id_index"

  create_table "friends", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "friend_user_id", :integer, :default => 0, :null => false
    t.column "friend_level", :integer, :default => 1, :null => false
  end

  create_table "preferences", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "deals_scroll_height", :string, :limit => 20
    t.column "color", :string, :limit => 32
    t.column "business_use", :boolean, :default => false, :null => false
    t.column "use_daily_booking", :boolean, :default => true, :null => false
  end

  create_table "settlements", :force => true do |t|
    t.column "user_id", :integer
    t.column "account_id", :integer
    t.column "name", :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "description", :text
  end

  create_table "users", :force => true do |t|
    t.column "login", :string, :limit => 80, :default => "", :null => false
    t.column "salted_password", :string, :limit => 40, :default => "", :null => false
    t.column "email", :string, :limit => 60, :default => "", :null => false
    t.column "firstname", :string, :limit => 40
    t.column "lastname", :string, :limit => 40
    t.column "salt", :string, :limit => 40, :default => "", :null => false
    t.column "verified", :integer, :default => 0
    t.column "role", :string, :limit => 40
    t.column "security_token", :string, :limit => 40
    t.column "token_expiry", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "logged_in_at", :datetime
    t.column "deleted", :integer, :default => 0
    t.column "delete_after", :datetime
  end

end
