# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 0) do

  create_table "account_entries", :force => true do |t|
    t.column "user_id", :integer, :null => false
    t.column "account_id", :integer, :null => false
    t.column "deal_id", :integer, :null => false
    t.column "amount", :integer, :null => false
    t.column "balance", :integer
    t.column "friend_link_id", :integer
  end

  create_table "account_links", :id => false, :force => true do |t|
    t.column "account_id", :integer, :null => false
    t.column "connected_account_id", :integer, :null => false
  end

  create_table "account_rules", :force => true do |t|
    t.column "user_id", :integer, :null => false
    t.column "account_id", :integer, :null => false
    t.column "associated_account_id", :integer, :null => false
    t.column "closing_day", :integer, :default => 0, :null => false
    t.column "payment_term_months", :integer, :default => 1, :null => false
    t.column "payment_day", :integer, :default => 0, :null => false
  end

  create_table "accounts", :force => true do |t|
    t.column "user_id", :integer, :null => false
    t.column "name", :string, :limit => 32, :null => false
    t.column "account_type", :integer, :null => false
    t.column "asset_type", :integer
    t.column "sort_key", :integer
    t.column "partner_account_id", :integer
  end

# Could not dump table "deal_links" because of following StandardError
#   Unknown type '' for column 'created_user_id'

  create_table "deals", :force => true do |t|
    t.column "type", :string, :limit => 20, :null => false
    t.column "user_id", :integer, :null => false
    t.column "date", :date, :null => false
    t.column "daily_seq", :integer, :null => false
    t.column "summary", :string, :limit => 64, :null => false
    t.column "confirmed", :boolean, :default => true, :null => false
    t.column "parent_deal_id", :integer
  end

  create_table "friend_deals", :force => true do |t|
    t.column "user_id", :integer, :null => false
    t.column "deal_id", :integer, :null => false
    t.column "friend_deal_id", :integer, :null => false
  end

  create_table "friends", :force => true do |t|
    t.column "user_id", :integer, :null => false
    t.column "friend_user_id", :integer, :null => false
    t.column "friend_level", :integer, :default => 1, :null => false
  end

  create_table "preferences", :force => true do |t|
    t.column "user_id", :integer, :null => false
    t.column "deals_scroll_height", :string, :limit => 20
  end

# Could not dump table "sqlite_sequence" because of following StandardError
#   Unknown type '' for column 'name'

  create_table "user2s", :force => true do |t|
    t.column "login_id", :string, :limit => 16, :null => false
    t.column "hashed_password", :string, :limit => 40, :null => false
  end

  add_index "user2s", ["login_id"], :name => "sqlite_autoindex_user2s_1", :unique => true

  create_table "users", :force => true do |t|
    t.column "login", :string, :limit => 80, :default => "", :null => false
    t.column "salted_password", :string, :limit => 40, :default => "", :null => false
    t.column "email", :string, :limit => 60, :default => "", :null => false
    t.column "firstname", :string, :limit => 40
    t.column "lastname", :string, :limit => 40
    t.column "salt", :string, :limit => 40, :default => "", :null => false
    t.column "verified", :integer, :default => 0
    t.column "role", :string, :limit => 40
    t.column "security_token", :string, :limit => 40
    t.column "token_expiry", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "logged_in_at", :datetime
    t.column "deleted", :integer, :default => 0
    t.column "delete_after", :datetime
  end

end
